# Generated by Django 2.2.3 on 2020-01-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191103_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '博客'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '博客分类'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '博客标签'},
        ),
    ]
