name: Python application

on:
  push:
    branches:
    - master

jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: macadmin
          MYSQL_DATABASE: blog
          MYSQL_ROOT_PASSWORD: macadmin
      
  build:
    name: deploy to development
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv -i https://pypi.douban.com/simple

    - name: run blog
      run: |
        cd Dblog && python manage.py migrate && python manage.py runserver

    
