name: Python application

on:
  push:
    branches:
    - master

jobs:
  build:
    name: deploy to development
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv -i https://pypi.douban.com/simple

    - name: run blog
      run: |
        cd Dblog && python manage.py migrate && python manage.py runserver
